export const BlogData = [
    {
        id: 1,
        blogheading:'The Cheapest Way To Earn Your Free Ticket To',
        blogdata:'Its a long established fact that reader will distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
        blogimg:'https://www.urjaglobal.in/images/4.jpg',
        date:'11 MAY 2020',
        postby:'Urja Global',
    },
    {
        id: 2,
        blogheading:'The Cheapest Way To Earn Your Free Ticket To',
        blogdata:'Its a long established fact that reader will distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
        blogimg:'https://www.urjaglobal.in/images/4.jpg',
        date:'11 MAY 2020',
        postby:'Urja Global',
    },
    {
        id: 3,
        blogheading:'The Cheapest Way To Earn Your Free Ticket To',
        blogdata:'Its a long established fact that reader will distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
        blogimg:'https://www.urjaglobal.in/images/4.jpg',
        date:'11 MAY 2020',
        postby:'Urja Global',
    },
    {
        id: 4,
        blogheading:'The Cheapest Way To Earn Your Free Ticket To',
        blogdata:'Its a long established fact that reader will distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
        blogimg:'https://www.urjaglobal.in/images/4.jpg',
        date:'11 MAY 2020',
        postby:'Urja Global',
    },
    {
        id: 5,
        blogheading:'The Cheapest Way To Earn Your Free Ticket To',
        blogdata:'Its a long established fact that reader will distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
        blogimg:'https://www.urjaglobal.in/images/4.jpg',
        date:'11 MAY 2020',
        postby:'Urja Global',
    },
    {
        id: 6,
        blogheading:'The Cheapest Way To Earn Your Free Ticket To',
        blogdata:'Its a long established fact that reader will distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.',
        blogimg:'https://www.urjaglobal.in/images/4.jpg',
        date:'11 MAY 2020',
        postby:'Urja Global',
    },
]